---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: controller
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolume
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - clusterissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - acmeservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - acmeservers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - applications
    verbs:
      - get
      - list
  - apiGroups:
      - core.kalm.dev
    resources:
      - componentpluginbindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - componentpluginbindings/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - componentplugins
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - componentplugins/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - components
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - components/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - dnsrecords
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - dnsrecords/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - dockerregistries
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - dockerregistries/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - domains
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - domains/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - httproutes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - httproutes/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - httpscertissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - httpscertissuers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - httpscerts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - httpscerts/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - logsystems
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - logsystems/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - protectedendpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - protectedendpoints/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.kalm.dev
    resources:
      - singlesignonconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.kalm.dev
    resources:
      - singlesignonconfigs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - dex.coreos.com
    resources:
      - "*"
    verbs:
      - create
  - apiGroups:
      - extensions
    resources:
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - destinationrules
    verbs:
      - "*"
  - apiGroups:
      - networking.istio.io
    resources:
      - envoyfilters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - envoyfilters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - networking.istio.io
    resources:
      - gateways
    verbs:
      - "*"
  - apiGroups:
      - networking.istio.io
    resources:
      - serviceentries
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - serviceentries/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - "*"
  - apiGroups:
      - security.istio.io
    resources:
      - authorizationpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - security.istio.io
    resources:
      - authorizationpolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - security.istio.io
    resources:
      - requestauthentications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - security.istio.io
    resources:
      - requestauthentications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
